# Site settings
name: ä»°æœ›æ˜Ÿç©ºï¼Œè„šè¸å®åœ°
email: yangdy@aliyun.com
author: yangdy
url: http://yangdy.com
resume_site: http://yangdy.com/me/
github: https://github.com/yangdy-buji/
baseurl: ""  #æ ¹ç›®å½•
description: å¿ƒæ€€æ¢¦æƒ³ï¼Œä¸ç•å¯‚å¯
motto: æˆ‘ä»¬çš„å¾ç¨‹æ˜¯æ˜Ÿè¾°å¤§æµ·
banner: æ¬¢è¿æ¥é¢†é˜¿é‡Œäº‘å¹¸è¿åˆ¸ï¼Œä½ æ˜¯æœ€å¹¸è¿çš„äºº ğŸ‘
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #æ–‡ç« æ‘˜è¦
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: yangdy-buji
highlighter: rouge
markdown: kramdown
